# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Einstein
  first_name: [Albert, A.]

  style: apa
  locale: en
  sort_by: year, month

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
